import type { IBoard } from "~/types/task.interface";
import type { IUser } from "~/types/user.interface";

export const ISAUTH = false;

export const MainUser: IUser = {
  id: "user_1",
  name: "amigo",
  email: "denrizuk@gmail.com",
  password: "dasjrkl321qwnrd",
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const Boards: IBoard[] = [
  {
    id: "1",
    name: "Board 1",
    sections: [
      {
        id: "section_1_id",
        name: "TODO",
        tasksCount: 2,
        color: "black",
        tasks: [
          {
            id: "task_1_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: MainUser,
            deadline: new Date(),
            priority: "P1",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "task_2_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: [MainUser, MainUser],
            deadline: new Date(),
            priority: "P3",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "task_3_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: MainUser,
            deadline: new Date(),
            priority: "P2",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "section_2_id",
        name: "Done",
        tasksCount: 2,
        color: "black",
        tasks: [
          {
            id: "task_12_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: MainUser,
            deadline: new Date(),
            priority: "P1",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "task_23_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Bag",
            assigned: [MainUser, MainUser],
            deadline: new Date(),
            priority: "P3",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "section_3_id",
        name: "Test",
        tasksCount: 2,
        color: "black",
        tasks: [
          {
            id: "task_16_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: MainUser,
            deadline: new Date(),
            priority: "P1",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "task_21_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: [MainUser, MainUser],
            deadline: new Date(),
            priority: "P3",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            id: "task_33_id",
            name: "Create landing with design on figma",
            description: "Create landing with design on figma",
            creator: MainUser,
            taskType: "Task",
            assigned: MainUser,
            deadline: new Date(),
            priority: "P2",
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    userCreator: MainUser,
    users: [],
    accessability: "private",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Board 2",
    sections: [],
    userCreator: MainUser,
    users: [],
    accessability: "private",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
